Fatal error if utils.sh is missing
Fatal error if utils.sh is missing

diff --git a/check_glusterfs b/check_glusterfs
--- a/check_glusterfs
+++ b/check_glusterfs
@@ -37,6 +37,9 @@ REVISION="1.0.3"
 if [ -f $PROGPATH/utils.sh ]
 then
         . $PROGPATH/utils.sh
+else
+		echo "Fatal error, missing $PROGPATH/utils.sh"
+		exit 1
 fi
 
 # parse command line
